test: Disable gometalinter as it fails to install
To be replaced in the near future with golangci-lint, which fully
replaces gometalinter in terms of functionality, plus adds some more.

    # gopkg.in/alecthomas/gometalinter.v1
    Error: ../../../../pkg/mod/gopkg.in/alecthomas/gometalinter.v1@v1.2.1/main.go:129:69: cannot use loadConfig (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to kingpin.Flag("config", "Load JSON configuration from file.").Action
    Error: ../../../../pkg/mod/gopkg.in/alecthomas/gometalinter.v1@v1.2.1/main.go:130:104: cannot use disableAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to kingpin.Flag("disable", "Disable previously enabled linters.").PlaceHolder("LINTER").Short('D').Action
    Error: ../../../../pkg/mod/gopkg.in/alecthomas/gometalinter.v1@v1.2.1/main.go:131:103: cannot use enableAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to kingpin.Flag("enable", "Enable previously disabled linters.").PlaceHolder("LINTER").Short('E').Action
    Error: ../../../../pkg/mod/gopkg.in/alecthomas/gometalinter.v1@v1.2.1/main.go:135:60: cannot use disableAllAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to kingpin.Flag("disable-all", "Disable all linters.").Action
    Error: ../../../../pkg/mod/gopkg.in/alecthomas/gometalinter.v1@v1.2.1/main.go:136:58: cannot use enableAllAction (type func(*kingpin.Application, *kingpin.ParseElement, *kingpin.ParseContext) error) as type kingpin.Action in argument to kingpin.Flag("enable-all", "Enable all linters.").Action

Signed-off-by: Joe Groocock <me@frebib.net>